name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    env:
      AZURE_WEBAPP_NAME: Search-Engine-1718133629013
      AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
      JAVA_VERSION: '17'
      AZURE_WEBAPP_FTPS_CREDENTIALS: ${{ secrets.AZURE_WEBAPP_FTPS_CREDENTIALS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package -B

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_FTPS_CREDENTIALS }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'
